/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ControllerLayer;

import BusinessLayer.Customer;
import BusinessLayer.Items;
import BusinessLayer.MAIN;
import BusinessLayer.restaurant;
import DataLayer.RestuarantData;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zain
 */
public class RestaurantHomepaageGUI extends javax.swing.JFrame {

                   ///////////////////////////////////////////////////
                   ////////////Connecting to BusinessLayer////////////
                   ///////////////////////////////////////////////////
    RestaurantLogInGUI obj=new RestaurantLogInGUI ();
    private restaurant rest_obj=new restaurant();
    private ArrayList<restaurant> rest=rest_obj.getData();
    public RestaurantHomepaageGUI() {
        String temp="x";
//        int count=0;
        initComponents(); 
        String Restaurant=obj.check;
        REST.setText(Restaurant);
        
        DefaultTableModel tblMode2=(DefaultTableModel)jTable2.getModel();
        for(Customer a:Customer.getData())
        {
            for(int i=0;i<a.orders.size();i++)
            {
                if(a.orders.get(i).getRestaurant().equals(Restaurant)) 
                {
                   
                    String name[]={a.getEmail()};
                    
                    if(!temp.equals(a.getEmail())){
                    tblMode2.addRow(name);
                    temp=a.getEmail();}
                }
            }  
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ItemName = new javax.swing.JTextField();
        checkCustomer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        AddToMenuButton = new javax.swing.JButton();
        PrizeInput = new javax.swing.JTextField();
        UpdateMenuButton = new javax.swing.JButton();
        REST = new javax.swing.JLabel();
        back1 = new javax.swing.JButton();
        BackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        ItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemNameActionPerformed(evt);
            }
        });
        jPanel1.add(ItemName);
        ItemName.setBounds(219, 200, 250, 22);

        checkCustomer.setBackground(new java.awt.Color(0, 255, 255));
        checkCustomer.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        checkCustomer.setText("CHECK DETAILS");
        checkCustomer.setBorderPainted(false);
        checkCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(checkCustomer);
        checkCustomer.setBounds(690, 280, 140, 30);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ORDERS FROM"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(560, 180, 410, 70);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer", "Item", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(560, 400, 410, 140);

        AddToMenuButton.setBackground(new java.awt.Color(0, 255, 255));
        AddToMenuButton.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        AddToMenuButton.setText("ADD TO MENU");
        AddToMenuButton.setBorderPainted(false);
        AddToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToMenuButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddToMenuButton);
        AddToMenuButton.setBounds(230, 370, 150, 30);

        PrizeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrizeInputActionPerformed(evt);
            }
        });
        jPanel1.add(PrizeInput);
        PrizeInput.setBounds(220, 300, 250, 22);

        UpdateMenuButton.setBackground(new java.awt.Color(0, 255, 255));
        UpdateMenuButton.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        UpdateMenuButton.setText("UPDATE MENU");
        UpdateMenuButton.setBorderPainted(false);
        UpdateMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateMenuButtonActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateMenuButton);
        UpdateMenuButton.setBounds(230, 420, 150, 30);

        REST.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jPanel1.add(REST);
        REST.setBounds(160, 30, 400, 30);

        back1.setBackground(new java.awt.Color(0, 255, 255));
        back1.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        back1.setText("SIGN OUT");
        back1.setBorderPainted(false);
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });
        jPanel1.add(back1);
        back1.setBounds(10, 510, 120, 40);

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterfaceLayer/RestaurantHomepaage.png"))); // NOI18N
        jPanel1.add(BackGround);
        BackGround.setBounds(0, 0, 1020, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1028, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateMenuButtonActionPerformed
    
        new UpdateMenuItemsGUI().setVisible(true);  
this.dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_UpdateMenuButtonActionPerformed

    private void PrizeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrizeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrizeInputActionPerformed
    boolean flag=true;
    private void AddToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToMenuButtonActionPerformed
        if(ItemName.getText().isEmpty()||PrizeInput.getText().isEmpty())
             {
           JOptionPane.showMessageDialog(null,"PLEASE ENTER ALL FILEDS");
           flag=false;
       }
        if(flag)
        {
            if(rest_obj.checkItemExistance(REST.getText(), ItemName.getText()))
            {
                            JOptionPane.showMessageDialog(null,"ITEM ALREADY EXIST");
                            flag=false;
            }
            
        }
        if (flag)
        {
            rest_obj.addItem(ItemName.getText(), REST.getText(), PrizeInput.getText());
            JOptionPane.showMessageDialog(null,"ITEM ADDED SUCCESSFULLY");

        }        
    }//GEN-LAST:event_AddToMenuButtonActionPerformed

    private void ItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemNameActionPerformed
    String selected;
    private void checkCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCustomerActionPerformed
              
       DefaultTableModel tblMode2=(DefaultTableModel)jTable1.getModel();
       
       if(jTable2.getRowCount()>0)
       {
            selected=jTable2.getValueAt(jTable2.getSelectedRow(),0).toString();  
       }
       
           DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
    int k=tblModel.getRowCount();
    for(int j=k-1;j>=0;j--)
    {
        tblModel.removeRow(j);
     
    }

                   ///////////////////////////////////////////////////
                   ////////////Connecting to BusinessLayer////////////
                   ///////////////////////////////////////////////////
      
       
           
            for(Customer a:Customer.getData()){
                if(a.getEmail().equals(selected))
                {
                    for(int i=0;i<a.orders.size();i++)
                    {
                    String name=a.getEmail();
                    int quantity=a.orders.get(i).getQuantity();
                    String stringQuantity=String.valueOf(quantity);
                    String item=a.orders.get(i).getItem().toString();
                    String order[]={name,item,stringQuantity};
                    tblModel.addRow(order); 
                    }
                    
                  
                }

            }
       
       
       
       
       
       
       
       
    
       
    }//GEN-LAST:event_checkCustomerActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        new RestaurantLogInGUI().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_back1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurantHomepaageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurantHomepaageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurantHomepaageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurantHomepaageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurantHomepaageGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToMenuButton;
    private javax.swing.JLabel BackGround;
    private javax.swing.JTextField ItemName;
    private javax.swing.JTextField PrizeInput;
    private javax.swing.JLabel REST;
    private javax.swing.JButton UpdateMenuButton;
    private javax.swing.JButton back1;
    private javax.swing.JButton checkCustomer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
