/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ControllerLayer;

import BusinessLayer.Customer;
import BusinessLayer.MAIN;
import BusinessLayer.Orders;
import BusinessLayer.Rider;
import DataLayer.CustomerData;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zain
 */
public class RiderHomepaageGUI extends javax.swing.JFrame {

    /**
     * Creates new form RiderHomepaageGUI
     */
    private static String check1;
    private Rider Rider_obj;
    private Orders order_obj;
    
    public RiderHomepaageGUI() {
        initComponents();
        String temp="x";
        RiderLogin riderss=new RiderLogin();
        RiderNameWelcomeLabel.setText(riderss.check3);
        
        
        DefaultTableModel tblMode1=(DefaultTableModel)jTable1.getModel();
   
                for(Customer a:Customer.getData())
        {
            for(int i=0;i<a.orders.size();i++)
            {
                if(a.obj.isIsPickedUp()==false){
                                   
                    String name[]={a.getEmail(),a.getAddress(),a.orders.get(i).getRestaurant().toString()};
                    if(!temp.equals(a.getEmail()))
                    {
                    tblMode1.addRow(name);
                    temp=a.getEmail();
                    
                    }
                } 
            }
           
        }
                
                for(Rider r: Rider.getData())
                {
                    if(r.getEmail().equals(RiderNameWelcomeLabel.getText()))
                    {
                    if(r.isIsBusy())
                    {
                        CustomerName.setText(r.getTempCust());
                        Address.setText(r.getTempAdress());
                        rest_name.setText(r.getTempRestuarant());
                    }
                }
                }
                
                
        
         status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Picked", "Delivered" }));
        

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ORDERACCEPT = new javax.swing.JButton();
        status = new javax.swing.JComboBox<>();
        rest_name = new javax.swing.JTextField();
        CustomerName = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        RiderNameWelcomeLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        back1 = new javax.swing.JButton();
        UpdateDeleveryStatusButton = new javax.swing.JButton();
        Background = new javax.swing.JLabel();
        AcceptOrderButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        ORDERACCEPT.setBackground(new java.awt.Color(0, 255, 255));
        ORDERACCEPT.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        ORDERACCEPT.setText("ACCEPT ORDER");
        ORDERACCEPT.setBorderPainted(false);
        ORDERACCEPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ORDERACCEPTActionPerformed(evt);
            }
        });
        jPanel1.add(ORDERACCEPT);
        ORDERACCEPT.setBounds(200, 460, 160, 23);

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(status);
        status.setBounds(710, 390, 100, 22);

        rest_name.setEditable(false);
        jPanel1.add(rest_name);
        rest_name.setBounds(740, 330, 170, 40);

        CustomerName.setEditable(false);
        jPanel1.add(CustomerName);
        CustomerName.setBounds(740, 210, 170, 40);

        Address.setEditable(false);
        jPanel1.add(Address);
        Address.setBounds(740, 270, 170, 40);

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jLabel2.setText("CUSTOMER NAME");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(610, 230, 120, 15);

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jLabel3.setText("DELIVERY ADDRESS");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(610, 280, 130, 15);

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jLabel4.setText("RESTAURNAT  NAME");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(610, 340, 130, 15);

        RiderNameWelcomeLabel.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jPanel1.add(RiderNameWelcomeLabel);
        RiderNameWelcomeLabel.setBounds(270, 30, 260, 30);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer", "Customer Addrress", "Restaurant"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(110, 180, 340, 240);

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel1.setText("WELCOME ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 30, 110, 30);

        back1.setBackground(new java.awt.Color(0, 255, 255));
        back1.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        back1.setText("SIGN OUT");
        back1.setBorderPainted(false);
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });
        jPanel1.add(back1);
        back1.setBounds(30, 510, 120, 40);

        UpdateDeleveryStatusButton.setBackground(new java.awt.Color(0, 255, 255));
        UpdateDeleveryStatusButton.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        UpdateDeleveryStatusButton.setText("UPDATE STATUS");
        UpdateDeleveryStatusButton.setBorderPainted(false);
        UpdateDeleveryStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDeleveryStatusButtonActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateDeleveryStatusButton);
        UpdateDeleveryStatusButton.setBounds(670, 460, 150, 30);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterfaceLayer/RiderHomepaage.png"))); // NOI18N
        jPanel1.add(Background);
        Background.setBounds(0, 0, 1020, 570);

        AcceptOrderButton1.setBackground(new java.awt.Color(0, 255, 255));
        AcceptOrderButton1.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        AcceptOrderButton1.setText("ACCEPT ORDER");
        AcceptOrderButton1.setBorderPainted(false);
        AcceptOrderButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptOrderButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(AcceptOrderButton1);
        AcceptOrderButton1.setBounds(200, 460, 160, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1028, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        new RiderLogin().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_back1ActionPerformed

    private void UpdateDeleveryStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDeleveryStatusButtonActionPerformed
       int checkStatus=status.getSelectedIndex();
       String check_Status=status.getItemAt(checkStatus);
       if(check_Status.equals("Delivered"))
       {
           for(Rider r:Rider.getData())
           {
               if(r.getEmail().equals(RiderNameWelcomeLabel.getText()))
               {
                   r.setIsBusy(false);   
                   for(Customer c:Customer.getData())
                   {
                       if(c.getEmail().equals(CustomerName.getText()))
                       {
                           c.obj.setFlag(true);
                           c.obj.setCancel(true);
                           for(int i=0;i<c.orders.size();i++)
                           {
                                DefaultTableModel tblMode1=(DefaultTableModel)jTable1.getModel();
                                for(int j=0;j<tblMode1.getRowCount();j++)
                                {
                                    if(tblMode1.getValueAt(j,0).equals(c.getEmail()))
                                    {
                                        tblMode1.removeRow(j);
                                    }
                                }
                               
                               CustomerName.setText("");
                               Address.setText("");
                               rest_name.setText("");
                               c.orders.remove(i);
                               Rider.write();
                               Customer.write();
                               break;
                               
                           }
                           
                       }
                   }
                   
                   
                   
                   CustomerName.setText("");
                   Address.setText("");
                   rest_name.setText("");
                   break;
               }
           }
       }
       else
       {
           
            for(Rider r:Rider.getData())
           {
               if(r.getEmail().equals(RiderNameWelcomeLabel.getText()))
               {
                   if(r.isIsBusy())
                   {
                            for(Customer c:Customer.getData())
           {
               if(c.getEmail().equals(CustomerName.getText()))
               {
                   for(int i=0;i<c.orders.size();i++)
                   {
                       c.obj.setCancel(false);
                   }
               }
               
           }  
                       
                   }
               }
           }
       
           
       }
       
      
    }//GEN-LAST:event_UpdateDeleveryStatusButtonActionPerformed

    private void AcceptOrderButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptOrderButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcceptOrderButton1ActionPerformed
    
    int  selected;
    private void ORDERACCEPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ORDERACCEPTActionPerformed
       
        
        
        
        if(jTable1.getRowCount()>0)
       {
        selected=jTable1.getSelectedRow();
        DefaultTableModel tblMode1=(DefaultTableModel)jTable1.getModel();
        if(Rider_obj.AcceptDelivery(RiderNameWelcomeLabel.getText(), tblMode1.getValueAt(selected,0).toString(),CustomerName.getText()
        ,Address.getText(),rest_name.getText()))
        {
            CustomerName.setText(tblMode1.getValueAt(selected,0).toString());
            Address.setText(tblMode1.getValueAt(selected,1).toString());
            rest_name.setText(tblMode1.getValueAt(selected,2).toString());
            
        }
        else
             JOptionPane.showMessageDialog(null,"YOUR ARE ALREADY ON YOUR ODER"); 

       }
        else
        {
            JOptionPane.showMessageDialog(null,"PLEASE SELECT THE ORDER"); 
        }
       


// TODO add your handling code here:
    }//GEN-LAST:event_ORDERACCEPTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RiderHomepaageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RiderHomepaageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RiderHomepaageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RiderHomepaageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RiderHomepaageGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptOrderButton1;
    private javax.swing.JTextField Address;
    private javax.swing.JLabel Background;
    private javax.swing.JTextField CustomerName;
    private javax.swing.JButton ORDERACCEPT;
    private javax.swing.JLabel RiderNameWelcomeLabel;
    private javax.swing.JButton UpdateDeleveryStatusButton;
    private javax.swing.JButton back1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField rest_name;
    private javax.swing.JComboBox<String> status;
    // End of variables declaration//GEN-END:variables
}
