/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ControllerLayer;

import BusinessLayer.Customer;
import BusinessLayer.MAIN;
import DataLayer.CustomerData;
import javax.swing.JOptionPane;

/**
 *
 * @author Zain
 */
public class TrackOrderGUI extends javax.swing.JFrame {

    /**
     * Creates new form TrackOrderGUI
     */
    private Customer cust_obj=new Customer();
    public TrackOrderGUI() {
        initComponents();
        LogInGUI obj= new LogInGUI();
        CustomerName.setText(obj.check);
        if(cust_obj.trackOrder(CustomerName.getText()))
            RiderStatusLabel.setText("ACTIVE"); 
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        CustomerName = new javax.swing.JLabel();
        DeleveryStatusLabel = new javax.swing.JLabel();
        RiderStatusLabel = new javax.swing.JLabel();
        CookingStatusLabel = new javax.swing.JLabel();
        CancelOrderButton = new javax.swing.JButton();
        back = new javax.swing.JButton();
        Backgroud = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setLayout(null);
        jPanel2.add(CustomerName);
        CustomerName.setBounds(240, 30, 120, 0);
        jPanel2.add(DeleveryStatusLabel);
        DeleveryStatusLabel.setBounds(660, 400, 110, 20);
        jPanel2.add(RiderStatusLabel);
        RiderStatusLabel.setBounds(500, 400, 110, 20);

        CookingStatusLabel.setText("ACTIVE");
        jPanel2.add(CookingStatusLabel);
        CookingStatusLabel.setBounds(360, 404, 80, 20);

        CancelOrderButton.setBackground(new java.awt.Color(0, 255, 255));
        CancelOrderButton.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        CancelOrderButton.setText("CANCEL ORDER");
        CancelOrderButton.setBorderPainted(false);
        CancelOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelOrderButtonActionPerformed(evt);
            }
        });
        jPanel2.add(CancelOrderButton);
        CancelOrderButton.setBounds(460, 453, 150, 30);

        back.setBackground(new java.awt.Color(0, 255, 255));
        back.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        back.setText("BACK");
        back.setBorderPainted(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel2.add(back);
        back.setBounds(880, 520, 120, 40);

        Backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/TrackOrder.png"))); // NOI18N
        jPanel2.add(Backgroud);
        Backgroud.setBounds(0, 0, 1012, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1028, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelOrderButtonActionPerformed
     
        if(cust_obj.cancelOrder(CustomerName.getText()))
            JOptionPane.showMessageDialog(null,"CANCEL FAILED, YOUR ORDER IS NOW GETTING READY. ");
        else
        {
            JOptionPane.showMessageDialog(null,"CANCELLED SUCCESSFULLY ");
            new CustomerHomepageGUI().setVisible(true);

        }
    }//GEN-LAST:event_CancelOrderButtonActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new CustomerHomepageGUI().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrackOrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrackOrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrackOrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrackOrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrackOrderGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backgroud;
    private javax.swing.JButton CancelOrderButton;
    private javax.swing.JLabel CookingStatusLabel;
    private javax.swing.JLabel CustomerName;
    private javax.swing.JLabel DeleveryStatusLabel;
    private javax.swing.JLabel RiderStatusLabel;
    private javax.swing.JButton back;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
