/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ControllerLayer;

/**
 *
 * @author Zain
 */
public class UpdateCartGUI extends javax.swing.JFrame {

    /**
     * Creates new form UpdateCartGUI
     */
    public UpdateCartGUI() {
        initComponents();
        ResturantNameUpdateCart.setText(CustomerHomepageGUI.check1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UpdateCartItemDropDown = new javax.swing.JComboBox<>();
        UpdateCartQuantityCounter = new javax.swing.JSpinner();
        ResturantNameUpdateCart = new javax.swing.JLabel();
        DeleteItemButton2 = new javax.swing.JButton();
        UpdateItemCartButton = new javax.swing.JButton();
        back = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        UpdateCartItemDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(UpdateCartItemDropDown);
        UpdateCartItemDropDown.setBounds(400, 300, 260, 22);
        jPanel1.add(UpdateCartQuantityCounter);
        UpdateCartQuantityCounter.setBounds(400, 390, 260, 22);

        ResturantNameUpdateCart.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jPanel1.add(ResturantNameUpdateCart);
        ResturantNameUpdateCart.setBounds(330, 160, 320, 30);

        DeleteItemButton2.setBackground(new java.awt.Color(0, 255, 255));
        DeleteItemButton2.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        DeleteItemButton2.setText("DELETE ITEM");
        DeleteItemButton2.setBorderPainted(false);
        DeleteItemButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteItemButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteItemButton2);
        DeleteItemButton2.setBounds(320, 467, 150, 30);

        UpdateItemCartButton.setBackground(new java.awt.Color(0, 255, 255));
        UpdateItemCartButton.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        UpdateItemCartButton.setText("UPDATE MENU");
        UpdateItemCartButton.setBorderPainted(false);
        UpdateItemCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateItemCartButtonActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateItemCartButton);
        UpdateItemCartButton.setBounds(510, 470, 150, 23);

        back.setBackground(new java.awt.Color(0, 255, 255));
        back.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        back.setText("BACK");
        back.setBorderPainted(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(880, 520, 120, 40);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/UpdateCart.png"))); // NOI18N
        jPanel1.add(Background);
        Background.setBounds(0, 0, 1020, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1028, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteItemButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteItemButton2ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_DeleteItemButton2ActionPerformed

    private void UpdateItemCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateItemCartButtonActionPerformed

     
    }//GEN-LAST:event_UpdateItemCartButtonActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new CustomerHomepageGUI().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateCartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateCartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateCartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateCartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateCartGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton DeleteItemButton2;
    private javax.swing.JLabel ResturantNameUpdateCart;
    private javax.swing.JComboBox<String> UpdateCartItemDropDown;
    private javax.swing.JSpinner UpdateCartQuantityCounter;
    private javax.swing.JButton UpdateItemCartButton;
    private javax.swing.JButton back;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
